# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='TypeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.UserType'),
            preserve_default=False,
        ),
    ]
