# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_assert_userinfo_temp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assert',
            new_name='Asset',
        ),
    ]
